# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WsGen < Formula
  desc "WebSocket client and server generation tool"
  homepage "https://github.com/Dafaque/ws-gen"
  version "0.1.0"
  license "TBA"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.1.0/ws-gen_0.1.0_darwin_amd64.tar.gz"
      sha256 "46a670ed8c7f4c1628e37bf76e7a7ee0a78ad9214a690ad66870e9f3e4410d5c"

      def install
        bin.install "ws-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.1.0/ws-gen_0.1.0_darwin_arm64.tar.gz"
      sha256 "ee4d6b8516afc9b9090ecc9e7ef0d4e4c562527d9817bf7aae1bc41e1942b8c8"

      def install
        bin.install "ws-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.1.0/ws-gen_0.1.0_linux_amd64.tar.gz"
      sha256 "fd4ca535de00a85ae2a2ae6b61585014f891837947168b15ba92c44d0748f711"

      def install
        bin.install "ws-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.1.0/ws-gen_0.1.0_linux_arm64.tar.gz"
      sha256 "872766ab07f937ff45ed5aad1a55f65b9d432fde015c0ccbb9b374d5bcae7217"

      def install
        bin.install "ws-gen"
      end
    end
  end

  def caveats
    <<~EOS
      ws-gen -h
    EOS
  end
end
