# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WsGen < Formula
  desc "WebSocket client and server generation tool"
  homepage "https://github.com/Dafaque/ws-gen"
  version "0.3.3"
  license "TBA"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.3.3/ws-gen_0.3.3_darwin_amd64.tar.gz"
      sha256 "e8c991b1b97f19f2de355514fe32db300b0c62d906f05ff3537fc8697e5ba1e1"

      def install
        bin.install "ws-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.3.3/ws-gen_0.3.3_darwin_arm64.tar.gz"
      sha256 "a26c4282ce8ee80401181275c235a0098353610e66537bc88657129cfc4a5b49"

      def install
        bin.install "ws-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.3.3/ws-gen_0.3.3_linux_amd64.tar.gz"
      sha256 "5d5ac92e7650c7618b48f7bf876e1dc2014c82d541cd5b01882c1338007ddae5"

      def install
        bin.install "ws-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dafaque/ws-gen/releases/download/v0.3.3/ws-gen_0.3.3_linux_arm64.tar.gz"
      sha256 "f0e3990bd7ce2dce5dccf6a643a309978facdd76db9d1834f2d528d2ce66b2f4"

      def install
        bin.install "ws-gen"
      end
    end
  end

  def caveats
    <<~EOS
      ws-gen -h
    EOS
  end
end
